services:
  web:
    build: .
    ports:
      - '5000:5000'
    restart: always
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

      # for SQLAlchemy
      - DATABASE_URL=mysql+pymysql://mindcare_user:mindcare_password@mindcare-1.cfxz9clxyucm.us-east-1.rds.amazonaws.com/mindcare_db

      # for entrypoint.sh MySQL checks
      - DB_HOST=mindcare-1.cfxz9clxyucm.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_USER=mindcare_user
      - DB_PASS=mindcare_password
      - SIGN_UP_API_GATEWAY_URL=https://5awie7nwk1.execute-api.us-east-1.amazonaws.com/prod/signup

    networks:
      - mindcare-network

networks:
  mindcare-network:
    driver: bridge
